name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQube:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.x'

    - name: Install Visual Studio Build Tools
      run: |
        choco install visualstudio2022buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.ManagedDesktopBuildTools --includeRecommended --includeOptional"
        choco install visualstudio2022-workload-netweb --package-parameters "--includeRecommended --includeOptional"

    - name: Install NuGet
      run: choco install nuget.commandline

    - name: Install vswhere
      run: choco install vswhere

    - name: Find MSBuild Path
      id: msbuild-path
      run: |
        $msbuildPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
        echo "##[set-output name=msbuild_path;]$msbuildPath"

    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Restore dependencies
      run: nuget restore

    - name: Build solution
      run: |
        $msbuildPath = "${{ steps.msbuild-path.outputs.msbuild_path }}"
        & $msbuildPath /p:Configuration=Release /p:Platform="Any CPU"

    - name: Run tests and collect code coverage
      run: |
        $msbuildPath = "${{ steps.msbuild-path.outputs.msbuild_path }}"
        dotnet test --collect:"XPlat Code Coverage"

    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Run SonarQube Analysis
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        dotnet sonarscanner begin /k:"TonyYourFriend_sonarqubetest_d5ca3011-0da9-4380-b605-ea742cd704cc" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
          /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" `
          /d:sonar.cs.vstest.reportsPaths="**/*.trx" `
          /d:sonar.scm.provider="git" `
          /d:sonar.coverage.exclusions="**/Migrations/**" `
          /d:sonar.cpd.exclusions="**/Test/**" `
          /d:sonar.exclusions="**/bin/**,**/obj/**,**/*.generated.cs" `
          /d:sonar.issue.ignore.multicriteria=e1,e2 `
          /d:sonar.issue.ignore.multicriteria.e1.ruleKey=csharpsquid:S1075 `
          /d:sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.cs `
          /d:sonar.issue.ignore.multicriteria.e2.ruleKey=csharpsquid:S100 `
          /d:sonar.issue.ignore.multicriteria.e2.resourceKey=**/*.cs `
          /d:sonar.tests="**/*Tests.cs" `
          /d:sonar.test.inclusions="**/*Tests.cs" `
          /d:sonar.test.exclusions="**/IntegrationTests/**"

        $msbuildPath = "${{ steps.msbuild-path.outputs.msbuild_path }}"
        & $msbuildPath /p:Configuration=Release /p:Platform="Any CPU"
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Publish Quality Gate Result
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        dotnet sonarscanner begin /k:"TonyYourFriend_sonarqubetest_d5ca3011-0da9-4380-b605-ea742cd704cc" `
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}" `
          /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}" `
          /d:sonar.qualitygate.wait=true

        $msbuildPath = "${{ steps.msbuild-path.outputs.msbuild_path }}"
        & $msbuildPath /p:Configuration=Release /p:Platform="Any CPU"
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
